import tailwindColors from 'tailwindcss/colors';

export const colors = {
  initial: 'initial',
  inherit: 'inherit',
  current: 'currentColor',
  transparent: 'transparent',
  background: tailwindColors.white,
  foreground: tailwindColors.slate[900],
  primary: tailwindColors.slate[900],
  'primary-foreground': tailwindColors.slate[50],
  secondary: tailwindColors.slate[100],
  'secondary-foreground': tailwindColors.slate[900],
  destructive: tailwindColors.red[500],
  'destructive-foreground': tailwindColors.slate[50],
  informative: tailwindColors.blue[50],
  'informative-foreground': tailwindColors.blue[700],
  success: tailwindColors.green[50],
  'success-foreground': tailwindColors.green[700],
  warning: tailwindColors.yellow[50],
  'warning-foreground': tailwindColors.yellow[700],
  accent: tailwindColors.slate[100],
  'accent-foreground': tailwindColors.slate[900],
  muted: tailwindColors.slate[100],
  'muted-foreground': tailwindColors.slate[500],
  ring: tailwindColors.slate[900],
  input: tailwindColors.slate[200],
  border: tailwindColors.slate[200],
  card: tailwindColors.white,
  'card-foreground': tailwindColors.slate[900],
  popover: tailwindColors.white,
  'popover-foreground': tailwindColors.slate[900],
  tooltip: tailwindColors.slate[900],
  'tooltip-foreground': tailwindColors.slate[50],
};
